In [1]:
import tensorflow as tf

a = tf.Variable([1,2,3,4,5])
b = tf.Variable([1,2,3,4,5])

In [6]:
import tensorflow as tf

# if tensorflow version is lower than 1.9.0
if tf.__version__ < "1.9.0":
    #sess = tf.InteractiveSession()
    sess = tf.Session()
    t1 = tf.Variable([1, 2, 3, 4])
    t2 = tf.Variable([5, 6, 7, 8])
    t3 = t1 + t2
    init = tf.global_variables_initializer()

    sess.run(init)
    print(sess.run(t3))

else:
    a = tf.Variable([1, 2, 3])
    b = tf.Variable([4, 5, 6])
    c = a + b
    print(c.numpy())





[ 6  8 10 12]


In [21]:
import tensorflow as tf
import numpy as np
lr = 0.5 #learning rate
#=================================================
# training data & place holder
#=================================================
t_data = [[0,0],[0,1],[1,0],[1,1]]
label = [[0],[1],[1],[0]]
t_data = np.array(t_data, dtype=np.float32)
label = np.array(label, dtype=np.float32)
X=tf.placeholder(tf.float32, [None,2])
Y=tf.placeholder(tf.float32, [None,1])
# =================================================
# Weight and Bias
# =================================================
W1=tf.Variable(tf.random_normal([2, 2]), name='weight1')
W2=tf.Variable(tf.random_normal([2, 1]), name='weight2')
b1=tf.Variable(tf.random_normal([2]), name='bias1')
b2=tf.Variable(tf.random_normal([1]), name='bias2')
# =================================================
# Operation graph
# =================================================
hidden = tf.sigmoid(tf.matmul(X,W1)+b1)
Y_ = tf.sigmoid(tf.matmul(hidden, W2)+b2)

# =================================================
# Training and verification graph
# =================================================
cost = -tf.reduce_mean(Y*tf.log(Y_)+(1-Y)*tf.log(1-Y_))
train = tf.train.GradientDescentOptimizer(learning_rate=lr).minimize(cost)
predicted = tf.cast(Y_>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))
# =================================================
# Run Session
# =================================================
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train,feed_dict={X:t_data, Y:label})
        if step % 100 == 0:
            print(step, sess.run(cost,feed_dict={X:t_data, Y:label}),sess.run(W))
            h,c,a=sess.run([Y_, predicted, accuracy], feed_dict={X:t_data, Y:label})
            print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)
            print(sess.run(W),sess.run(b))

0 0.872378 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.16460487]
 [ 0.21174024]
 [ 0.23953599]
 [ 0.27979046]] 
Correct:  [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 
Accuracy:  0.5
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
100 0.626626 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.36043721]
 [ 0.55383563]
 [ 0.53872925]
 [ 0.57262874]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy:  0.75
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
200 0.555217 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.26012951]
 [ 0.6146574 ]
 [ 0.57222539]
 [ 0.58300233]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy:  0.75
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
300 0.472892 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.19167575]
 [ 0.67379695]
 [ 0.61840016]
 [ 0.55216515]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy:  0.75
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
400 0.333914 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.16698667]
 [ 0.73585516]
 [ 0.7279104 ]
 [ 0.41060168]] 

4100 0.0053897 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00669103]
 [ 0.99514657]
 [ 0.99515235]
 [ 0.00510753]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
4200 0.00524074 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00651248]
 [ 0.99528116]
 [ 0.9952867 ]
 [ 0.0049624 ]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
4300 0.00509966 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00634313]
 [ 0.99540859]
 [ 0.99541402]
 [ 0.00482514]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
4400 0.00496591 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00618231]
 [ 0.99552947]
 [ 0.99553466]
 [ 0.00469517]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
4500 0.00483887 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00602936]
 [ 0.99564433]
 [ 0.99564916]
 [ 

7800 0.00261488 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00331233]
 [ 0.99765092]
 [ 0.99765283]
 [ 0.00243696]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
7900 0.00257877 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00326756]
 [ 0.99768341]
 [ 0.99768531]
 [ 0.00240268]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
8000 0.00254366 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00322398]
 [ 0.997715  ]
 [ 0.9977169 ]
 [ 0.00236935]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
8100 0.00250948 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.00318154]
 [ 0.99774581]
 [ 0.9977476 ]
 [ 0.00233693]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
[[-0.68260741]
 [-0.16322875]] [ 1.62427497]
8200 0.00247615 [[-0.68260741]
 [-0.16322875]]

Hypothesis:  [[ 0.0031402 ]
 [ 0.99777585]
 [ 0.99777764]
 [

In [ ]:
import tensorflow as tf
# =================================================
# read MNIST DB
# =================================================
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("data/", one_hot=True)
print('train dataset:', mnist.train.images.shape, mnist.train.labels.shape)
print('test dataset:', mnist.test.images.shape, mnist.test.labels.shape)
print('validation dataset:', mnist.validation.images.shape,
mnist.validation.labels.shape)

Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz


In [ ]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("data/", one_hot=True)
# =================================================
# placeholder to feed data to graph 28x28=784
# =================================================
x = tf.placeholder(tf.float32, [None, 784]) # data
y = tf.placeholder(tf.float32, [None, 10]) # label
# =================================================
# Weight and Bias
# =================================================
W = tf.Variable(tf.random_normal([784, 10], stddev=0.01))
# =================================================
# Operational graph
# =================================================
y_ = tf.nn.softmax(tf.matmul(x, W))
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y * tf.log(y_),
reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

# =================================================
# Data feed
# =================================================
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
# =================================================
# mini batch operation, batchsize=100
# =================================================
for i in range(2000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
    # =================================================
    # Verification
    # =================================================
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print(sess.run(accuracy, feed_dict={x: mnist.test.images, y: mnist.test.labels}))

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/t10k-labels-idx1-ubyte.gz


In [22]:
mnist = input_data.read_data_sets("data/", one_hot=True)
print('train dataset:', mnist.train.images.shape, mnist.train.labels.shape)
print('test dataset:', mnist.test.images.shape, mnist.test.labels.shape)
print('validation dataset:', mnist.validation.images.shape, mnist.validation.labels.shape)
# =================================================
# placeholder to feed data to graph 28x28=784
# =================================================
X = tf.placeholder(tf.float32, [None, 784]) # data
Y = tf.placeholder(tf.float32, [None, 10]) # label
# =================================================
# layer 1 processing
# =================================================
W1 = tf.Variable(tf.random_normal([784, 392], stddev=0.01))
L1 = tf.nn.relu(tf.matmul(X, W1))
# =================================================
# layer 2 processing
# =================================================
W2 = tf.Variable(tf.random_normal([392, 10], stddev=0.01))
L2 = tf.matmul(L1, W2)
cost = tf.reduce_mean(
tf.nn.softmax_cross_entropy_with_logits_v2(logits=L2, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)
# train_step=tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)
# =================================================
# Data feed
# =================================================
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)


NameError: name 'input_data' is not defined

In [23]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================]11493376/11490434 [==============================] - 2s 0us/step

