In [ ]:
"""tensorflow 기본적인 code 따라하기  Y= W*X +B"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

x_data = [1, 2, 3]
y_data = [1, 2, 3]

#making tensorflow structure
W = tf.Variable(tf.random_normal([1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

hypothesis = W*X + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

#training tensors

learning_rate = 0.1

#manual gradient
'''gradient = tf.reduce_mean((W*X - Y) * X)*2
descent = W - learning_rate * gradient
update = W.assign(descent)'''

#auto gradient
optimizer = tf.train.GradientDescentOptimizer(learning_rate= learning_rate).minimize(cost)
#get gradient '''minimize cost 부분'''
'''gvs = optimizer.compute_gradients(cost)
apply_gradients = optimizer.apply_gradients(gvs)
#버전 문제로 안돌아감'''



#train

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_value, w_value, b_value = sess.run([optimizer, cost, W, b], feed_dict = {X: x_data, Y:y_data})
        print(step, cost_value, w_value, b_value)
        

In [18]:
"""Lab 3 ZeroToAll github code"""
# Lab 3 Minimizing Cost
import tensorflow as tf

# tf Graph Input
x_data = [1, 2, 3]
y_data = [1, 2, 3]

# Set wrong model weights
W = tf.Variable(5.0)
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Linear model
hypothesis = X * W

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize: Gradient Descent Optimizer
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, W_val = sess.run([train, W], feed_dict = {X:x_data, Y:y_data})
        print(step, W_val)


0 1.26667
1 1.01778
2 1.00119
3 1.00008
4 1.00001
5 1.0
6 1.0
7 1.0
8 1.0
9 1.0
10 1.0
11 1.0
12 1.0
13 1.0
14 1.0
15 1.0
16 1.0
17 1.0
18 1.0
19 1.0
20 1.0
21 1.0
22 1.0
23 1.0
24 1.0
25 1.0
26 1.0
27 1.0
28 1.0
29 1.0
30 1.0
31 1.0
32 1.0
33 1.0
34 1.0
35 1.0
36 1.0
37 1.0
38 1.0
39 1.0
40 1.0
41 1.0
42 1.0
43 1.0
44 1.0
45 1.0
46 1.0
47 1.0
48 1.0
49 1.0
50 1.0
51 1.0
52 1.0
53 1.0
54 1.0
55 1.0
56 1.0
57 1.0
58 1.0
59 1.0
60 1.0
61 1.0
62 1.0
63 1.0
64 1.0
65 1.0
66 1.0
67 1.0
68 1.0
69 1.0
70 1.0
71 1.0
72 1.0
73 1.0
74 1.0
75 1.0
76 1.0
77 1.0
78 1.0
79 1.0
80 1.0
81 1.0
82 1.0
83 1.0
84 1.0
85 1.0
86 1.0
87 1.0
88 1.0
89 1.0
90 1.0
91 1.0
92 1.0
93 1.0
94 1.0
95 1.0
96 1.0
97 1.0
98 1.0
99 1.0
100 1.0


In [7]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

#making node
X = tf.placeholder(tf.float32, shape= [None, 3])
Y = tf.placeholder(tf.float32, shape= [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-5).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
        if step % 20 == 0 :
            print(step, cost_val,"\n", hy_val)


0 93137.8 
 [[-121.86820221]
 [-139.39080811]
 [-141.32637024]
 [-150.58866882]
 [-107.16174316]]
20 3.7543 
 [[ 148.92134094]
 [ 186.06575012]
 [ 179.35806274]
 [ 198.62614441]
 [ 141.07867432]]
40 3.74534 
 [[ 148.93037415]
 [ 186.06440735]
 [ 179.36322021]
 [ 198.62928772]
 [ 141.07669067]]
60 3.73647 
 [[ 148.93690491]
 [ 186.06011963]
 [ 179.36543274]
 [ 198.62924194]
 [ 141.07243347]]
80 3.72765 
 [[ 148.94337463]
 [ 186.05583191]
 [ 179.36763   ]
 [ 198.62915039]
 [ 141.06822205]]
100 3.7189 
 [[ 148.94984436]
 [ 186.05157471]
 [ 179.36982727]
 [ 198.62908936]
 [ 141.0640564 ]]
120 3.71023 
 [[ 148.95628357]
 [ 186.04736328]
 [ 179.37202454]
 [ 198.62902832]
 [ 141.05989075]]
140 3.7016 
 [[ 148.96266174]
 [ 186.0431366 ]
 [ 179.37419128]
 [ 198.62892151]
 [ 141.05575562]]
160 3.69304 
 [[ 148.96902466]
 [ 186.03894043]
 [ 179.37634277]
 [ 198.6288147 ]
 [ 141.051651  ]]
180 3.68457 
 [[ 148.9753418 ]
 [ 186.03474426]
 [ 179.37849426]
 [ 198.62872314]
 [ 141.04756165]]
200 3.676

1680 3.18847 
 [[ 149.37384033]
 [ 185.77394104]
 [ 179.51631165]
 [ 198.60629272]
 [ 140.80838013]]
1700 3.18329 
 [[ 149.37828064]
 [ 185.77105713]
 [ 179.51786804]
 [ 198.6058197 ]
 [ 140.80595398]]
1720 3.17817 
 [[ 149.38267517]
 [ 185.76820374]
 [ 179.51942444]
 [ 198.60536194]
 [ 140.80355835]]
1740 3.17306 
 [[ 149.38705444]
 [ 185.76535034]
 [ 179.52096558]
 [ 198.60487366]
 [ 140.80116272]]
1760 3.16798 
 [[ 149.39141846]
 [ 185.76252747]
 [ 179.52252197]
 [ 198.60440063]
 [ 140.79881287]]
1780 3.16293 
 [[ 149.39576721]
 [ 185.75971985]
 [ 179.52407837]
 [ 198.60392761]
 [ 140.79646301]]
1800 3.1579 
 [[ 149.40008545]
 [ 185.75691223]
 [ 179.52557373]
 [ 198.60342407]
 [ 140.79412842]]
1820 3.15291 
 [[ 149.40438843]
 [ 185.75413513]
 [ 179.52711487]
 [ 198.60293579]
 [ 140.79180908]]
1840 3.14794 
 [[ 149.40867615]
 [ 185.75134277]
 [ 179.52862549]
 [ 198.60244751]
 [ 140.789505  ]]
1860 3.143 
 [[ 149.41291809]
 [ 185.74858093]
 [ 179.53013611]
 [ 198.60192871]
 [ 140.7872

In [15]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv?raw=true', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#making node
X = tf.placeholder(tf.float32, shape= [None, 3])
Y = tf.placeholder(tf.float32, shape= [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-5).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 20 == 0 :
        print(step, cost_val,"\n", hy_val)


0 83346.1 
 [[-111.2884903 ]
 [-142.81196594]
 [-135.92431641]
 [-152.00349426]
 [-107.44599915]
 [ -85.5220871 ]
 [-116.46701813]
 [ -90.03569794]
 [-139.96192932]
 [-138.62849426]
 [-110.81866455]
 [-114.50258636]
 [-136.76980591]
 [-108.50828552]
 [-118.72074127]
 [-147.76333618]
 [-101.32131195]
 [-140.57867432]
 [-128.36166382]
 [-114.38768005]
 [-136.82647705]
 [-136.99311829]
 [-128.54484558]
 [-103.5167923 ]
 [-144.94303894]]
20 94.9525 
 [[ 159.91847229]
 [ 183.25704956]
 [ 185.30014038]
 [ 197.87599182]
 [ 141.22602844]
 [  97.89000702]
 [ 145.46299744]
 [ 104.18637848]
 [ 164.84765625]
 [ 143.80065918]
 [ 141.52536011]
 [ 134.37548828]
 [ 195.05862427]
 [ 167.28564453]
 [ 144.43330383]
 [ 183.150177  ]
 [ 161.31762695]
 [ 173.76533508]
 [ 187.96676636]
 [ 168.64726257]
 [ 170.32803345]
 [ 168.93743896]
 [ 164.28216553]
 [ 169.82910156]
 [ 192.95394897]]
40 93.4469 
 [[ 159.86289978]
 [ 183.29203796]
 [ 185.27876282]
 [ 197.89430237]
 [ 141.24368286]
 [  97.97912598]
 [ 145.5

500 65.1611 
 [[ 158.45376587]
 [ 183.68223572]
 [ 184.51837158]
 [ 197.93136597]
 [ 141.34529114]
 [  99.63260651]
 [ 146.23986816]
 [ 105.72575378]
 [ 166.86003113]
 [ 147.86460876]
 [ 141.99401855]
 [ 136.14974976]
 [ 193.36048889]
 [ 164.72369385]
 [ 145.64056396]
 [ 184.24412537]
 [ 158.45466614]
 [ 174.76397705]
 [ 185.86700439]
 [ 166.69657898]
 [ 171.23007202]
 [ 170.08181763]
 [ 164.698349  ]
 [ 166.27178955]
 [ 192.62406921]]
520 64.1694 
 [[ 158.39923096]
 [ 183.69692993]
 [ 184.48872375]
 [ 197.9329834 ]
 [ 141.34846497]
 [  99.69664001]
 [ 146.26898193]
 [ 105.78399658]
 [ 166.93382263]
 [ 148.01507568]
 [ 142.01115417]
 [ 136.21508789]
 [ 193.29650879]
 [ 164.62739563]
 [ 145.68556213]
 [ 184.28396606]
 [ 158.34667969]
 [ 174.80174255]
 [ 185.78826904]
 [ 166.62359619]
 [ 171.26368713]
 [ 170.12356567]
 [ 164.71391296]
 [ 166.13894653]
 [ 192.61070251]]
540 63.1948 
 [[ 158.34521484]
 [ 183.7114563 ]
 [ 184.45933533]
 [ 197.93460083]
 [ 141.35154724]
 [  99.7600708 ]
 [ 1

1060 42.9711 
 [[ 157.10809326]
 [ 184.03367615]
 [ 183.7804718 ]
 [ 197.9763031 ]
 [ 141.4024353 ]
 [ 101.21411133]
 [ 146.98304749]
 [ 107.21048737]
 [ 168.68202209]
 [ 151.60403442]
 [ 142.42538452]
 [ 137.76925659]
 [ 191.76344299]
 [ 162.31440735]
 [ 146.77516174]
 [ 185.22781372]
 [ 155.74049377]
 [ 175.73574829]
 [ 183.90629578]
 [ 164.88316345]
 [ 172.08229065]
 [ 171.11402893]
 [ 165.10197449]
 [ 162.96539307]
 [ 192.27922058]]
1080 42.3604 
 [[ 157.06640625]
 [ 184.04417419]
 [ 183.75738525]
 [ 197.97790527]
 [ 141.40339661]
 [ 101.26316071]
 [ 147.00701904]
 [ 107.25830078]
 [ 168.73851013]
 [ 151.72087097]
 [ 142.43907166]
 [ 137.81971741]
 [ 191.71325684]
 [ 162.23852539]
 [ 146.81126404]
 [ 185.2583313 ]
 [ 155.65454102]
 [ 175.76737976]
 [ 183.84489441]
 [ 164.82653809]
 [ 172.10957336]
 [ 171.14608765]
 [ 165.11524963]
 [ 162.86190796]
 [ 192.26795959]]
1100 41.7602 
 [[ 157.02513123]
 [ 184.05447388]
 [ 183.73449707]
 [ 197.97947693]
 [ 141.40429688]
 [ 101.3117218 ]
 

1620 29.2882 
 [[ 156.08088684]
 [ 184.28138733]
 [ 183.20578003]
 [ 198.01986694]
 [ 141.40730286]
 [ 102.4237442 ]
 [ 147.59527588]
 [ 108.43086243]
 [ 170.07528687]
 [ 154.50683594]
 [ 142.76953125]
 [ 139.01933289]
 [ 190.50993347]
 [ 160.41418457]
 [ 147.68569946]
 [ 185.98040771]
 [ 153.57769775]
 [ 176.54998779]
 [ 182.37651062]
 [ 163.47547913]
 [ 172.77484131]
 [ 171.90516663]
 [ 165.44572449]
 [ 160.38917542]
 [ 191.9876709 ]]
1640 28.9109 
 [[ 156.0491333 ]
 [ 184.28869629]
 [ 183.18780518]
 [ 198.02139282]
 [ 141.40672302]
 [ 102.46120453]
 [ 147.61503601]
 [ 108.47021484]
 [ 170.1184082 ]
 [ 154.59750366]
 [ 142.78044128]
 [ 139.0582428 ]
 [ 190.47052002]
 [ 160.35426331]
 [ 147.71469116]
 [ 186.00369263]
 [ 153.50909424]
 [ 176.57653809]
 [ 182.32858276]
 [ 163.43148804]
 [ 172.79702759]
 [ 171.9296875 ]
 [ 165.45700073]
 [ 160.30851746]
 [ 191.97814941]]
1660 28.5401 
 [[ 156.01766968]
 [ 184.29585266]
 [ 183.16996765]
 [ 198.02288818]
 [ 141.40611267]
 [ 102.49829865]
 

In [16]:
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 176.87217712]]
Other scores will be  [[ 149.74613953]
 [ 187.86949158]]
